{application, estdcoll,
    [{description, "Erlang Standard Collection Library"},
     {vsn, "0.1.0"},
     {modules, [b_collection,
                b_map,
                b_ordered_collection,
                b_random_access_collection,
                b_strict_collection,
                estdcoll,
                i_collection_list,
                i_map_dict,
                i_map_bg_tree]},
     {registered, []},
     {applications, [kernel, stdlib]},
     {env, []}]}.
